### ISSUE TITLE
Provide an example in the README and command line tool

### ISSUE THREAD

**Issue by paddykontschak** [Daij-Djan/DDMountainNotifier#1]
I'm not sure I understand how to use the command line tool correctly. The information I got from it are:

```
Usage: MountainNotifier caller(id|path|url) title [subtitle] [information] [icon(name|path|url)]
```

So I tried with `MountainNotifier com.apple.Terminal Appname 'New Mail' 'This Is A Test'`, which, after some trial and error, worked. But I still don't understand how to include the icon. And I have the feeling the caller didn't work either, because it's still showing the default spinning icon. With e.g. [terminal-notifier](https://github.com/alloy/terminal-notifier) I can see that NC uses the Terminal's icon when I tell him what ID I want to use.

For the icon I tried several ways:

```
MountainNotifier com.apple.Terminal Appname 'New Mail' 'This Is A Test' /Applications/Sublime\ Text\ 2.app/Contents/Resources/Sublime\ Text\ 2.icns
MountainNotifier com.apple.Terminal Appname 'New Mail' 'This Is A Test' '/Applications/Sublime\ Text\ 2.app/Contents/Resources/Sublime\ Text\ 2.icns'
MountainNotifier com.apple.Terminal Appname 'New Mail' 'This Is A Test' icon /Applications/Sublime\ Text\ 2.app/Contents/Resources/Sublime\ Text\ 2.icns
MountainNotifier com.apple.Terminal Appname 'New Mail' 'This Is A Test' icon '/Applications/Sublime\ Text\ 2.app/Contents/Resources/Sublime\ Text\ 2.icns'
MountainNotifier com.apple.Terminal Appname 'New Mail' 'This Is A Test' 'icon /Applications/Sublime\ Text\ 2.app/Contents/Resources/Sublime\ Text\ 2.icns'
MountainNotifier com.apple.Terminal Appname 'New Mail' 'This Is A Test' icon(/Applications/Sublime\ Text\ 2.app/Contents/Resources/Sublime\ Text\ 2.icns)
MountainNotifier com.apple.Terminal Appname 'New Mail' 'This Is A Test' 'icon(/Applications/Sublime\ Text\ 2.app/Contents/Resources/Sublime\ Text\ 2.icns)'
```

The icon hasn't changed at all. A simple example in the README or the helper text of the command line tool would be a big help.

**Comment by Daij-Djan** [comment]
:) the example is coming but you first way seemed correct...

> ./MountainNotifier com.apple.Terminal Appname 'New Mail' 'This Is A Test'
> 
> should definitly use the terminal's icon.
> good thing: it doesnt work for me either :D though it works for e.g. dropbox or skype

Ill look into it right now and update github
