### ISSUE TITLE
Proxy apps don't have correct icon

### ISSUE THREAD

**Issue by ponychicken** [Daij-Djan/DDMountainNotifier#2]
When I use the Growl plugin, I only get the Growl Icon for any app. If I send a notific. via Terminal, a proxy app with the correct icon is created.

**Comment by Daij-Djan** [comment]
Hi,
some / many apps that post growl notifications provide the app's icon as an alternate icon to the one normally shown.
I used that alternate icon and for my apps this worked perfect. For many though, it does not work.
I added an aditional fallback and that appears to work well :)

Please Remember to 'reset' mountainNotifier and the notification center by deleting ~/Library/Application Support/MountainNotifier AND reboot MountainLion.

code:
    if(!data) {
        NSString *appName = notification.applicationName;
        if(appName.length) {
            GrowlApplicationTicket *ticket = [[GrowlTicketController sharedController] ticketForApplicationName:appName hostName:nil];
            data = ticket.iconData;
        }
    }

**Comment by ponychicken** [comment]
Great, that did the trick!
